export const MODIFIERS = {
  disrupted: {
    position: 1,
    id: "disrupted",
    name: "Disrupt\n-ed",
    on: false,
    color: "bg-red-400",
    modifier: [-1, -1, -1],
    code: "DI",
  },
  frightened: {
    position: 2,
    id: "frightened",
    name: "Frighten\n-ed",
    on: false,
    color: "bg-red-400",
    modifier: [0, 0, 0],
    code: "No CA",
  },
  inTheYellow: {
    position: 3,
    id: "inTheYellow",
    name: "In the\nYellow",
    on: false,
    color: "bg-red-400",
    modifier: [-1, 0, 0],
    disabled: ["inTheRed"],
    code: "IY",
  },
  inTheRed: {
    position: 4,
    id: "inTheRed",
    name: "In the\nRed",
    on: false,
    color: "bg-red-400",
    modifier: [-2, 0, 0],
    disabled: ["inTheYellow"],
    code: "IR",
  },
  attackingToMyFlank: {
    position: 5,
    id: "attackingToMyFlank",
    name: "Attack\nmy Flank",
    on: false,
    color: "bg-red-400",
    modifier: [-1, 0, 0],
    code: "AMF",
    disabled: [
      "attackingToMyRear",
      "flanking",
      "pinching",
      "rearAttacking",
      "extremeRange",
      "longRange",
      "notClosestTarget",
      "fastMovingTarget",
      "moveAndShoot",
      "notClosestTarget",
    ],
  },
  attackingToMyRear: {
    position: 6,
    id: "attackingToMyRear",
    name: "Attack\nmy Rear",
    on: false,
    color: "bg-red-400",
    modifier: [0, -1, -1],
    code: "AMR",
    disabled: [
      "attackingToMyFlank",
      "flanking",
      "pinching",
      "rearAttacking",
      "extremeRange",
      "longRange",
      "notClosestTarget",
      "fastMovingTarget",
      "moveAndShoot",
      "notClosestTarget",
    ],
  },
  chargingFourOrMoreDice: {
    position: 7,
    id: "chargingFourOrMoreDice",
    name: "Charge\n4+ dice",
    on: false,
    color: "bg-green-400",
    modifier: [2, 0, 0],
    code: "CH",
    disabled: [
      "chargingThreeOrLessDice",
      "extremeRange",
      "longRange",
      "fastMovingTarget",
      "moveAndShoot",
      "notClosestTarget",
    ],
  },
  chargingThreeOrLessDice: {
    position: 8,
    id: "chargingThreeOrLessDice",
    name: "Charge\n3- dice",
    on: false,
    color: "bg-green-400",
    modifier: [1, 0, 0],
    code: "CH",
    disabled: [
      "chargingFourOrMoreDice",
      "extremeRange",
      "longRange",
      "fastMovingTarget",
      "moveAndShoot",
      "notClosestTarget",
    ],
  },
  flanking: {
    position: 9,
    id: "flanking",
    name: "Flanking\nEnemy",
    on: false,
    color: "bg-green-400",
    modifier: [0, 1, 0],
    code: "FL",
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "rearAttacking",
      "extremeRange",
      "longRange",
      "fastMovingTarget",
      "moveAndShoot",
      "notClosestTarget",
    ],
  },
  pinching: {
    position: 10,
    id: "pinching",
    name: "Pinching\nEnemy",
    on: false,
    color: "bg-green-400",
    modifier: [0, 1, 1],
    code: "PI",
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "extremeRange",
      "longRange",
      "fastMovingTarget",
      "moveAndShoot",
      "notClosestTarget",
    ],
  },
  rearAttacking: {
    position: 11,
    id: "rearAttacking",
    name: "Rear\nAttack",
    on: false,
    color: "bg-green-400",
    modifier: [0, 1, 1],
    code: "RA",
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "flanking",
      "extremeRange",
      "longRange",
      "fastMovingTarget",
      "fastMovingTarget",
      "extremeRange",
      "longRange",
      "moveAndShoot",
      "notClosestTarget",
    ],
  },
  calvaryTarget: {
    position: 12,
    id: "calvaryTarget",
    name: "Calvary\nTarget",
    on: false,
    color: "bg-red-400",
    modifier: [0, -1, 0],
    code: "CV",
  },
  collosalTarget: {
    position: 13,
    id: "collosalTarget",
    name: "Collosal\nTarget",
    on: false,
    color: "bg-green-400",
    modifier: [0, 2, 0],
    disabled: ["largeTarget"],
    code: "CO",
  },
  largeTarget: {
    position: 14,
    id: "largeTarget",
    name: "Large\nTarget",
    on: false,
    color: "bg-green-400",
    modifier: [0, 1, 0],
    disabled: ["collosalTarget"],
    code: "LG",
  },
  fastMovingTarget: {
    position: 15,
    id: "fastMovingTarget",
    name: "Fast\nTarget",
    on: false,
    color: "bg-red-400",
    modifier: [0, -1, 0],
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "chargingFourOrMoreDice",
      "chargingThreeOrLessDice",
      "flanking",
      "pinching",
      "rearAttacking",
    ],
    code: "FAST",
  },
  extremeRange: {
    position: 16,
    id: "extremeRange",
    name: "Extreme\nRange\n15+",
    on: false,
    color: "bg-red-400",
    modifier: [0, -2, 0],
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "chargingFourOrMoreDice",
      "chargingThreeOrLessDice",
      "flanking",
      "pinching",
      "rearAttacking",
      "longRange",
    ],
    code: "ER",
  },
  longRange: {
    position: 17,
    id: "longRange",
    name: "Long\nRange\n7-14",
    on: false,
    color: "bg-red-400",
    modifier: [0, -1, 0],
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "chargingFourOrMoreDice",
      "chargingThreeOrLessDice",
      "flanking",
      "pinching",
      "rearAttacking",
      "extremeRange",
    ],
    code: "LR",
  },
  moveAndShoot: {
    position: 18,
    id: "moveAndShoot",
    name: "Move &\nShoot",
    on: false,
    color: "bg-red-400",
    modifier: [0, -1, 0],
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "chargingFourOrMoreDice",
      "chargingThreeOrLessDice",
      "flanking",
      "pinching",
      "rearAttacking",
    ],
    code: "M&S",
  },
  notClosestTarget: {
    position: 19,
    id: "notClosestTarget",
    name: "Not\nClosest",
    on: false,
    color: "bg-red-400",
    modifier: [0, -1, 0],
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "chargingFourOrMoreDice",
      "chargingThreeOrLessDice",
      "flanking",
      "pinching",
      "rearAttacking",
    ],
    code: "NC",
  },
  reset: {
    position: 20,
    id: "reset",
    name: "Reset",
    on: true,
    color: "bg-yellow-400",
    modifier: [0, 0, 0],
  },
};

export const COMMAND_ACTION_MODIFIERS = [
  {
    id: "MinusOneDice",
    name: "-1\nDice",
    color: "bg-red-400",
    mod: [-1, 0, 0],
  },
  {
    id: "PlusOneDice",
    name: "+1\nDice",
    color: "bg-green-400",
    mod: [1, 0, 0],
  },
  {
    id: "MinusOneOS",
    name: "-1\nOS",
    color: "bg-red-400",
    mod: [0, -1, 0],
  },
  {
    id: "PlusOneOS",
    name: "+1\nOS",
    color: "bg-green-400",
    mod: [0, 1, 0],
  },
  {
    id: "MinusOneOP",
    name: "-1\nOP",
    color: "bg-red-400",
    mod: [0, 0, -1],
  },
  {
    id: "PlusOneOP",
    name: "+1\nOP",
    color: "bg-green-400",
    mod: [0, 0, 1],
  },
];
