// Map the semantic color tokens below onto grimdark plate styles — shared by
// the modifier grid and the rules-help action chips
export const PLATE_ON = {
  "bg-green-400": "plate-on-ember animate-ember-pulse",
  "bg-red-400": "plate-on-blood animate-blood-pulse",
  "bg-yellow-400": "plate-on-gold",
};

// `category` marks stance-specific modifiers — "melee" or "ranged" (absent
// means the modifier applies to both). The grid shows general modifiers plus
// the active stance's, and switching stance turns the other stance's off.
export const MODIFIERS = {
  disrupted: {
    position: 1,
    id: "disrupted",
    name: "Disrupt\n-ed",
    on: false,
    color: "bg-red-400",
    modifier: [-1, -1, -1],
    code: "DI",
  },
  frightened: {
    position: 2,
    id: "frightened",
    name: "Frighten\n-ed",
    on: false,
    color: "bg-red-400",
    modifier: [0, 0, 0],
    code: "No CC",
  },
  inTheYellow: {
    position: 3,
    id: "inTheYellow",
    name: "In the\nYellow",
    on: false,
    color: "bg-red-400",
    modifier: [-1, 0, 0],
    disabled: ["inTheRed"],
    code: "IY",
  },
  inTheRed: {
    position: 4,
    id: "inTheRed",
    name: "In the\nRed",
    on: false,
    color: "bg-red-400",
    modifier: [-2, 0, 0],
    disabled: ["inTheYellow"],
    code: "IR",
  },
  attackingToMyFlank: {
    position: 5,
    id: "attackingToMyFlank",
    category: "melee",
    name: "Attack\nmy Flank",
    on: false,
    color: "bg-red-400",
    modifier: [-1, 0, 0],
    code: "AMF",
    disabled: [
      "attackingToMyRear",
      "flanking",
      "pinching",
      "rearAttacking",
      "extremeRange",
      "longRange",
      "notClosestTarget",
      "fastMovingTarget",
      "moveAndShoot",
      "softCover",
      "hardCover",
    ],
  },
  attackingToMyRear: {
    position: 6,
    id: "attackingToMyRear",
    category: "melee",
    name: "Attack\nmy Rear",
    on: false,
    color: "bg-red-400",
    modifier: [0, -1, -1],
    code: "AMR",
    disabled: [
      "attackingToMyFlank",
      "flanking",
      "pinching",
      "rearAttacking",
      "extremeRange",
      "longRange",
      "notClosestTarget",
      "fastMovingTarget",
      "moveAndShoot",
      "softCover",
      "hardCover",
    ],
  },
  chargingFourOrMoreDice: {
    position: 7,
    id: "chargingFourOrMoreDice",
    category: "melee",
    name: "Charge\n4+ dice",
    on: false,
    color: "bg-green-400",
    modifier: [2, 0, 0],
    code: "CH",
    disabled: [
      "chargingThreeOrLessDice",
      "extremeRange",
      "longRange",
      "fastMovingTarget",
      "moveAndShoot",
      "notClosestTarget",
      "softCover",
      "hardCover",
    ],
  },
  chargingThreeOrLessDice: {
    position: 8,
    id: "chargingThreeOrLessDice",
    category: "melee",
    name: "Charge\n3- dice",
    on: false,
    color: "bg-green-400",
    modifier: [1, 0, 0],
    code: "CH",
    disabled: [
      "chargingFourOrMoreDice",
      "extremeRange",
      "longRange",
      "fastMovingTarget",
      "moveAndShoot",
      "notClosestTarget",
      "softCover",
      "hardCover",
    ],
  },
  flanking: {
    position: 9,
    id: "flanking",
    category: "melee",
    name: "Flanking\nEnemy",
    on: false,
    color: "bg-green-400",
    modifier: [0, 1, 0],
    code: "FL",
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "rearAttacking",
      "extremeRange",
      "longRange",
      "fastMovingTarget",
      "moveAndShoot",
      "notClosestTarget",
      "softCover",
      "hardCover",
    ],
  },
  pinching: {
    position: 10,
    id: "pinching",
    category: "melee",
    name: "Pinching\nEnemy",
    on: false,
    count: 0,
    maxCount: 3,
    color: "bg-green-400",
    modifier: [0, 1, 1],
    code: "PI",
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "extremeRange",
      "longRange",
      "fastMovingTarget",
      "moveAndShoot",
      "notClosestTarget",
      "softCover",
      "hardCover",
    ],
  },
  rearAttacking: {
    position: 11,
    id: "rearAttacking",
    category: "melee",
    name: "Rear\nAttack",
    on: false,
    color: "bg-green-400",
    modifier: [0, 1, 1],
    code: "RA",
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "flanking",
      "extremeRange",
      "longRange",
      "fastMovingTarget",
      "moveAndShoot",
      "notClosestTarget",
      "softCover",
      "hardCover",
    ],
  },
  cavalryTarget: {
    position: 12,
    id: "cavalryTarget",
    name: "Cavalry\nTarget",
    on: false,
    color: "bg-red-400",
    modifier: [0, -1, 0],
    code: "CV",
  },
  colossalTarget: {
    position: 13,
    id: "colossalTarget",
    name: "Colossal\nTarget",
    on: false,
    color: "bg-green-400",
    modifier: [0, 2, 0],
    disabled: ["largeTarget"],
    code: "CO",
  },
  largeTarget: {
    position: 14,
    id: "largeTarget",
    name: "Large\nTarget",
    on: false,
    color: "bg-green-400",
    modifier: [0, 1, 0],
    disabled: ["colossalTarget"],
    code: "LG",
  },
  // A state flag rather than a modifier in its own right: it carries no
  // triple, and exists so unit abilities that key off a wounded defender
  // (the Lizardmen's Blood Frenzy) have something to gate on.
  targetDamaged: {
    position: 15,
    id: "targetDamaged",
    category: "melee",
    name: "Foe\nDamaged",
    on: false,
    color: "bg-green-400",
    modifier: [0, 0, 0],
    code: "FD",
  },
  fastMovingTarget: {
    position: 16,
    id: "fastMovingTarget",
    category: "ranged",
    name: "Fast\nTarget",
    on: false,
    color: "bg-red-400",
    modifier: [0, -1, 0],
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "chargingFourOrMoreDice",
      "chargingThreeOrLessDice",
      "flanking",
      "pinching",
      "rearAttacking",
      "targetHighGround",
    ],
    code: "FAST",
  },
  extremeRange: {
    position: 17,
    id: "extremeRange",
    category: "ranged",
    name: "Extreme\nRange\n15+",
    on: false,
    color: "bg-red-400",
    modifier: [0, -2, 0],
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "chargingFourOrMoreDice",
      "chargingThreeOrLessDice",
      "flanking",
      "pinching",
      "rearAttacking",
      "longRange",
      "targetHighGround",
    ],
    code: "ER",
  },
  longRange: {
    position: 18,
    id: "longRange",
    category: "ranged",
    name: "Long\nRange\n7-14",
    on: false,
    color: "bg-red-400",
    modifier: [0, -1, 0],
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "chargingFourOrMoreDice",
      "chargingThreeOrLessDice",
      "flanking",
      "pinching",
      "rearAttacking",
      "extremeRange",
      "targetHighGround",
    ],
    code: "LR",
  },
  moveAndShoot: {
    position: 19,
    id: "moveAndShoot",
    category: "ranged",
    name: "Move &\nShoot",
    on: false,
    color: "bg-red-400",
    modifier: [0, -1, 0],
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "chargingFourOrMoreDice",
      "chargingThreeOrLessDice",
      "flanking",
      "pinching",
      "rearAttacking",
      "targetHighGround",
    ],
    code: "M&S",
  },
  notClosestTarget: {
    position: 20,
    id: "notClosestTarget",
    category: "ranged",
    name: "Not\nClosest",
    on: false,
    color: "bg-red-400",
    modifier: [0, -1, 0],
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "chargingFourOrMoreDice",
      "chargingThreeOrLessDice",
      "flanking",
      "pinching",
      "rearAttacking",
      "targetHighGround",
    ],
    code: "NC",
  },
  targetHighGround: {
    position: 21,
    id: "targetHighGround",
    category: "melee",
    name: "High\nGround",
    on: false,
    color: "bg-red-400",
    modifier: [0, -1, 0],
    disabled: [
      "extremeRange",
      "longRange",
      "fastMovingTarget",
      "moveAndShoot",
      "notClosestTarget",
    ],
    code: "HG",
  },
  softCover: {
    position: 22,
    id: "softCover",
    category: "ranged",
    name: "Soft\nCover",
    on: false,
    color: "bg-red-400",
    modifier: [0, -1, 0],
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "chargingFourOrMoreDice",
      "chargingThreeOrLessDice",
      "flanking",
      "pinching",
      "rearAttacking",
      "hardCover",
    ],
    code: "SC",
  },
  hardCover: {
    position: 23,
    id: "hardCover",
    category: "ranged",
    name: "Hard\nCover",
    on: false,
    color: "bg-red-400",
    modifier: [0, -2, 0],
    disabled: [
      "attackingToMyFlank",
      "attackingToMyRear",
      "chargingFourOrMoreDice",
      "chargingThreeOrLessDice",
      "flanking",
      "pinching",
      "rearAttacking",
      "softCover",
    ],
    code: "HC",
  },
  reset: {
    position: 24,
    id: "reset",
    name: "Reset",
    on: true,
    color: "bg-yellow-400",
    modifier: [0, 0, 0],
  },
};

export const COMMAND_CARD_MODIFIERS = [
  {
    id: "MinusOneDice",
    name: "-1\nDice",
    color: "bg-red-400",
    mod: [-1, 0, 0],
  },
  {
    id: "PlusOneDice",
    name: "+1\nDice",
    color: "bg-green-400",
    mod: [1, 0, 0],
  },
  {
    id: "MinusOneOS",
    name: "-1\nOS",
    color: "bg-red-400",
    mod: [0, -1, 0],
  },
  {
    id: "PlusOneOS",
    name: "+1\nOS",
    color: "bg-green-400",
    mod: [0, 1, 0],
  },
  {
    id: "MinusOneOP",
    name: "-1\nOP",
    color: "bg-red-400",
    mod: [0, 0, -1],
  },
  {
    id: "PlusOneOP",
    name: "+1\nOP",
    color: "bg-green-400",
    mod: [0, 0, 1],
  },
];
